spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 9999

#logging:
#  level:
#    org.springframework.cloud.config: DEBUG
#    org.springframework.cloud.context.properties: TRACE