spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # - note: path is environment-specific (keep in mind for future Docker/CI migration)
          search-locations: file:///E:/githubprojects/cloud-setup/cloud-config-properties/{application}/
          #search-locations: file:///mnt/e/githubprojects/cloud-setup/cloud-config-properties/{application} for WSL

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
